server:
  port: 8080
  mode: "debug"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "blog_system"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

jwt:
  secret_key: "123456789"
  expire_hours: 72

logging:
  level: "info"
  format: "json"
  output: "logs/blog.log"